site_name: depot-service

docs_dir: docs

nav:
  - Home: index.md
  - BPMN: business-process.md
  - Carwash: Car-Wash.bpmn
  - Safety & Emergency: Safety.feature
  - Management: Managing.feature

plugins:
  - techdocs-core
  # - bpmn-js:
  #     viewer_js: "https://unpkg.com/bpmn-js@18/dist/bpmn-navigated-viewer.production.min.js"
  #     viewer_css: "https://unpkg.com/bpmn-js@18/dist/assets/bpmn-js.css"
  #     class: "mk-bpmn-js"

theme:
  name: material
  features:
    - content.tooltips

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
