name: Buid and publish

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false

    - name: Set up npm authentication for GitHub Packages
      if: matrix.node-version == '20.x'
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
        echo "registry=https://npm.pkg.github.com/TripleBetaBV" >> ~/.npmrc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare package for publishing
      if: matrix.node-version == '20.x'
      run: |
        mkdir -p dist
        cp feature2markdown.js dist/
        cp fix-feature-references.js dist/

    - name: Publish to GitHub Packages
      if: matrix.node-version == '20.x'
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}